language: c
# env: export DISPLAY=:1.0
addons:
  apt:
    packages:
    # - arduino
    - xvfb
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"'
  - sleep 3s
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
script: make verify
